name: Exploring Workflow Dispatch Trigger

on:
  workflow_dispatch:
    inputs:
      custom_message:
        type: string
        descriprion: "Enter a custom message"  
        required: true

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Exploring Workflow Dispatch Trigger"

  job2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{inputs.custom_message}}"     